
name: Update GitHub B

on:
  push:
    branches:
      - main # Change this to the branch you want to monitor

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Update GitHub B
      run: |
        git config --global user.name "aditya"
        git config --global user.email "aditya@gmail.com"
        git clone https://github.com/devops-team-poc/terraform-poc.git
        git push https://devops-team-poc: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X@github.com/devops-team-poc/terraform-poc.git


      env:
        GH_B_TOKEN: ${{ secrets.GH_B_TOKEN }}
