name: Update GitHub A

on:
  push:
    branches:
      - main # Change this to the branch you want to monitor

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Set Up Git
        run: |
          git config user.name "devops-team-poc"
          git config user.email "devops.consultancy@ongraph.com"
          git remote add githubA https://github.com/devops-team-poc/terraform-poc.git
          git config credential.helper store
          echo "https://github.com/devops-team-poc/terraform-poc.git" > ~/.git-credentials
          echo "username=devops-team-poc" >> ~/.git-credentials
          echo "password=${{ secrets.GH_B_TOKEN }}" >> ~/.git-credentials

      - name: Update GitHub B
        run: |
          git push 
