name: Update GitHub B

on:
  push:
    branches:
      - main # Change this to the branch you want to monitor

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v3

    - name: Set Up Git
      run: |
        git config --global user.name "aditya"
        git config --global user.email "aditya@gmail.com"
        git remote add githubA https://github.com/devops-team-poc/terraform-poc.git
        git config --global credential.helper store
        git credential approve <https://github.com/devops-team-poc/terraform-poc.git>
        protocol=https
        host=github.com
        username=devops-team-poc
        password=${{ secrets.GH_B_TOKEN }}

    - name: Update GitHub B
      run: |
        git push githubA main
