
name: Update GitHub B

on:
  push:
    branches:
      - main # Change this to the branch you want to monitor

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Code
      uses: actions/checkout@v2

    - name: Update GitHub B
      run: |
        git config --global user.name "aditya"
        git config --global user.email "aditya@gmail.com"
        git remote add githubB https://github.com/devops-team-poc/terraform-poc.git
        echo $GH_B_TOKEN
        git push githubB main
        git push https://devops-team-poc:${{ secrets.GH_B_TOKEN }}@github.com/devops-team-poc/terraform-poc.git


      env:
        GH_B_TOKEN: ${{ secrets.GH_B_TOKEN }}
