name: Update GitHub B

on:
  push:
    branches:
      - main

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2

      - name: Update GitHub B
        run: |
          git config --global user.name "aditya"
          git config --global user.email "aditya@gmail.com"
          git clone https://github.com/AdityaKumarMishra/REACT.git
          cd terraform-poc  # Change to the cloned repository directory
          # Make your changes here
          git checkout -b main
          git add .
          git commit -m "Update something"
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_B_TOKEN }}
